== Asciidoc environment Setup

These scripts and files configure a users environment to allow the easy editing and viewing of asciidoc files.

It assumes the asciidoc files are stored in isub-directories within the ~/Documents/asciidoc directory.

[horizontal]
~/Documents/asciidoc/adoc;; Asciidoc source files
~/Documents/asciidoc/html;; html files generated by the ascidoc command
~/Documents/asciidoc/pdf;; pdf files generated by the wkhtmltopdf command. This uses the generated html files as input.

An alias is created called lvad. This alias lists the contents of the ~/Documents/asciidoc/adoc directory.

A function called vad is created. This function takes the name of a file (with or without an adoc extension) and opens or creates it (using vi) within the ~/Documents/asciidoc/adoc directory. It also opens the evince pdf viewer when started and closes it when the vi editor is closed.

=== Packages and Applications

The following packages are needed.

* evince
** or another pdf viewer that automatically updates the view of a pdf file when the file on disk changes.

* incrond
** this is available from the FC20 repositories.

* wkhtmltopdf
** A patched version of QT must be installed if using a binary that uses shared libraries.

 or

** A statically compiled version of wkhtmltopdf that was compiled against the patched version of QT must be used.
*** http://code.google.com/p/wkhtmltopdf/downloads/list?q=label:Deprecated
*** http://code.google.com/p/wkhtmltopdf/downloads/detail?name=wkhtmltoimage-0.11.0_rc1-static-amd64.tar.bz2&can=4&q=


=== Vim Configuration


==== Syntax Highlighting

Place the asciidoc.vim file into the ~/.vim/ftdetect directory

Download Dag Wieers asciidoc syntax file from his GitHub repository.
https://github.com/dagwieers/asciidoc-vim/blob/master/syntax/asciidoc.vim

Rename Dags asciidoc.vim file to ${HOME}/.vim/syntax/Dagsasciidoc.vim

Syntax highlighting should now be enabled.

==== Vim Keymappings

Rename or include the contents of the the vimrc file to ~/.vimrc

The included vimrc file defines the following:

[horizontal]
~/Documents/vimspell.add;; Defines a custom spellcheck file. Enable this by "set spell"

Backspace;; Clears any leftover highlighting from any searches.

Ctrl-Up;; Moves the current line up in the file.
Ctrl-Down;; Moves the current line down in the file.

Ctrl-b;; bold the current word or selection(visual mode)
Ctrl-i;; italicize the current word or selection(visual mode)
Ctrl-i;; mono the current word or selection(visual mode)

Alt-2 or Esc-2;; *RA-File style (bold)
Alt-3 or Esc-3;; *RA-Generic style (underline)
Alt-4 or Esc-4;; *RA-Important Term style (underline, mono)
Alt-5 or Esc-5;; *RA-Software Name style (underline, mono)
Alt-6 or Esc-6;; *RA-UI Element style (bold)
Alt-7 or Esc-7;; *RA-Variable Data style (underline, bold, mono)





=== Bash Configuration

==== Functions and Aliases

Rename or include the contents of the bashrc file to ~/.bashrc


==== Autocomplete for vad function

To enable auto completion for the vad function that displays the adoc files already existing, place the vad_autocomplete file into the /etc/bash_autocompletion.d directory.


==== Automatically generating html and pdf files

Place the adoc_process.sh script into the ~/bin directory.

Copy the incron file to the /var/spool/incron directory. 
Make sure to rename the file to the users login name and set the owner/group to root/USERNAME and the permissions to 0600.

The incrond daemon must be restarted to reload the configuration.



